### ISSUE TITLE
Original project commit history

### ISSUE THREAD

**Issue by zombah** [Cacti/plugin_weathermap#11]
Hello,
Thank you for attempt to continue work on weathermap for Cacti 1.x but it is very
unconfortable that you squashed all previous commits with "initial commit", please
consider to fork original repo and cherry-pick changes atop of it.

**Comment by TheWitness** [comment]
That's going to be real hard.  There is a very large pull request coming in here: https://github.com/Cacti/plugin_weathermap/pull/39

Once in beta, I would appreciate it if in the case you find an issue, just opening a ticket.

**Comment by TheWitness** [comment]
I'm not saying that I disagree with you.  But there are only so many hours in a day.  This incoming pull request was well over 100 man hours of personal time that I put into this project.
