### ISSUE TITLE
Plugin disables itself - Call  to a member function add_hint() on null in file

### ISSUE THREAD

**Issue by misterjmw** [Cacti/plugin_weathermap#4]
````
2020/03/24 07:44:45 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
--
2020/03/24 07:44:45 - ERROR PHP ERROR in  Plugin 'weathermap': Call  to a member function add_hint() on null in file:  /var/lib/cacti/plugins/weathermap/lib/Weathermap.class.php on line: 2260
2020/03/24 07:44:45 - WEATHERMAP WARNING: [Map 3] bpce.conf: Unrecognised config on line 195: BANDWIDTH 10G
2020/03/24 07:44:45 - WEATHERMAP WARNING: [Map 3] bpce.conf: Unrecognised config on line 194: VIA 294 474
````

**Comment by thurban** [comment]
This may have something to do with the bpce.conf file.   Can you make sure it does not contain any errors or temporarly disabled/move it and test with a plain config file ?

**Comment by misterjmw** [comment]
@thurban I started digging in when I didn't hear on this. There are quite a few errors actually, but it was a working map in the original 0.98a (IIRC) version of Weathermap. Do you want the errors it's throwing?

**Comment by TheWitness** [comment]
@misterjmw, please note below...

This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
