### ISSUE TITLE
Hover is not working

### ISSUE THREAD

**Issue by pradeepspa** [Cacti/plugin_weathermap#7]
I have installed this plugin on a latest cacti version 1.2.11. Looks like hover function is not working even though html style is chose "Overlib". Is hover not supported with this version?

**Comment by jpobeda** [comment]
@pradeepspa if you go to settings/General and look for

```
Allow Unsafe JavaScript eval() calls
Certain Cacti plugins require the use of unsafe JavaScript eval() calls. If you select this option, they will be allowed in Cacti.
```
Set it to Yes and that should resolve your problem.

**Comment by DoubleBeast** [comment]
> 
> 
> @pradeepspa if you go to settings/General and look for
> 
> ```
> Allow Unsafe JavaScript eval() calls
> Certain Cacti plugins require the use of unsafe JavaScript eval() calls. If you select this option, they will be allowed in Cacti.
> ```
> 
> Set it to Yes and that should resolve your problem.

I confirm that this solve the hover problem, this issue should be closed.

**Comment by jamesbtate** [comment]
Actually this was (partially) fixed in a merge commit on the master branch. See https://github.com/thurban/plugin_weathermap/commit/2314cf1547ff3563dbf3b23e18feb2d827ce1804

Also, "unsafe" is in the name of the option... It is a workaround, not a fix. Please try the master branch of this repo.

**Comment by DoubleBeast** [comment]
> 
> 
> Actually this was (partially) fixed in a merge commit on the master branch. See [2314cf1](https://github.com/thurban/plugin_weathermap/commit/2314cf1547ff3563dbf3b23e18feb2d827ce1804)
> 
> Also, "unsafe" is in the name of the option... It is a workaround, not a fix. Please try the master branch of this repo.

you are right, it is solved in the master branch, thanks for the info.

**Comment by metrotyranno** [comment]
I've just had the same issue. I installed from the master branch. Console started erroring that overlib.js was not found. I copied the overlib.js from plugins/weathermap to the root installation and the error went away. However Now I'm getting the following error:

overlib.js:1146 Uncaught TypeError: Cannot read property 'clientWidth' of undefined
    at windowWidth (overlib.js:1146)
    at placeLayer (overlib.js:568)
    at runHook (overlib.js:1437)
    at disp (overlib.js:525)
    at runHook (overlib.js:1437)
    at olMain (overlib.js:443)
    at runHook (overlib.js:1437)

overlib.js seems to use this fixscroll div a couple of times, however on the page source it does not exist. Manually creating this div resolves the issue.

**Comment by thurban** [comment]
Hi
That clientWidth statement on line 1146 of overlib.js is only in the development branch. Are you sure you took the file from the master branch ?

**Comment by metrotyranno** [comment]
I think the file was cached by my browser. I did a empty cache and reload. When I manually created the div, the hover graph's corner was right on the mouse. Now after the reset the graph is offset from the mouse. Is this intentional or is there still going something wrong.

**Comment by metrotyranno** [comment]
I have also noticed. When you use the weathermap menu button the hovering does not work. If you refresh the page it starts working again. There are no errors in the console though.

**Comment by zuka1337** [comment]
On my tests it only works with the console open(?)  cuz it forces the javasc call /o/

Cacti 1.2.16
Weathermap Master

**Comment by zuka1337** [comment]
![image](https://user-images.githubusercontent.com/57998098/114438784-1c8d9900-9bc0-11eb-96de-5e41739e1ab8.png)

**Comment by TheWitness** [comment]
@metrotyranno, @zuka1337, @DoubleBeast, @jamesbtate, @jpobeda, @pradeepspa see the note below..  Overlib will be gone after this.

This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
